package: dd_journal
version: '1.0.0'
author: Disch Development
supportpage: https://www.dischdev.com

page:
    title: 'Beiträge'
    perm: dd[manual]
    block: manual
    prio: 2
    icon: rex-icon fa-book
    pjax: true
